### ISSUE TITLE
[BUG] 用户css的背景颜色会覆盖waylyrics透明背景

### ISSUE THREAD

**Issue by ShuiHuo** [waylyrics/waylyrics#104]
~/.config/gtk-4.0/gtk.css 中写有用户自定义的背景颜色时，waylyrics透明背景不工作

@taoky 提供的 workaround:

```css
window#main-window { background-color: unset; }
```

将以上代码写入 `~/.config/gtk-4.0/gtk.css`

其他解决方案:

1. bubblewrap
2. 总之让 waylyrics 读不了 `~/.config/gtk-4.0/gtk.css`

> 在 sway 中启动 waylyrics 后，waylyrics 是一个普通的窗口界面，背景为白色。要怎么设置才能让它的背景变成透明？
>
> ![swappy-20231005-154440](https://github.com/waylyrics/waylyrics/assets/7471938/748af543-0ef1-429c-ab6b-18b240d9cb73)

**Comment by ShuiHuo** [comment]
> 请给一下 `~/.config/waylyrics/config.toml` 的内容。

[config.toml.txt](https://github.com/waylyrics/waylyrics/files/12813970/config.toml.txt)  上传到 GitHub 加了个`.txt`后缀

**Comment by taoky** [comment]
目前的代码主题设置逻辑是：https://github.com/waylyrics/waylyrics/blob/7304cc3f15e48a493cdd938b441053497bcfce59/src/main.rs#L75-L87

1. `theme_dir` 为 `~/.local/share/waylyrics/_themes`，检查 `theme_dir/{theme}.css` 是否存在，`{theme}` 为设置中的主题名；
2. 如果存在则使用，否则使用 Preset 值，`THEME_PRESETS_DIR` 为编译期的环境变量 `WAYLYRICS_THEME_PRESETS_DIR`。

目前最新版本的 theme 为：

```css
window#main-window {
    background-color: rgba(0, 0, 0, 0.0);
}

/* 标题栏的标题也是 label，因此需要特别指定 above 和 below */
label#above, label#below {
    /* 圆角 */
    border-radius: 16px;

    font-size: 28px;
    color: rgba(255, 255, 255, 1.0);
    background-color: rgba(0, 0, 0, 0.3);
    padding: 10px;
}

label#below {
    border-radius: 12px;
    margin: 5px 0px;
    font-size: 24px;
    padding: 7px;
}

/* 减少 Gtk CSD 的阴影 */
window {
    box-shadow: 0px 0px 1px 0px;
}

/* 设置 headerbar 为 50% 不透明度 */
headerbar {
    opacity: 0.5;
}
```

从你的截图看，`background-color`中 `rgba` 最后一项的值应该为 `0.0`。

**Comment by taoky** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/color_value/rgb#values

`rgb()` (`rgba()`) 最后一项值为不透明度 (opacity)，值为 1 时即为完全不透明，因此在你的 CSS 设置下背景为白色。

**Comment by ShuiHuo** [comment]
> `background-color`中 `rgba` 最后一项的值应该为 `0.0`

默认配置就没有背景透明。我设置主题改过这个值（0，0.0，0.5 这些都试过），窗口也没发生任何变化。

**Comment by taoky** [comment]
> > `background-color`中 `rgba` 最后一项的值应该为 `0.0`
> 
> 默认配置就没有背景透明。我设置主题改过这个值（0，0.0，0.5 这些都试过），窗口也没发生任何变化。

我在 nested sway 下不能复现这个问题，因此这和具体使用的混成器应该是无关的：

![image](https://github.com/waylyrics/waylyrics/assets/2109893/edf94849-07a5-4f2b-8f10-ef907b2acd63)

**Comment by taoky** [comment]
可以编译一下最新的 master 分支，然后加上 `RUST_LOG=waylyrics=debug` 环境变量运行。输出会显示使用的配置文件和主题文件的路径。

**Comment by poly000** [comment]
> > 请给一下 `~/.config/waylyrics/config.toml` 的内容。
> 
> [config.toml.txt](https://github.com/waylyrics/waylyrics/files/12813970/config.toml.txt) 上传到 GitHub 加了个`.txt`后缀

可以麻烦po一下您的
` ~/.local/share/waylyrics/themes/zhijiao.css ` 嘛
我找找sway wm本身会不会有影响它的设置

**Comment by poly000** [comment]
@ShuiHuo https://github.com/swaywm/sway/issues/973

**Comment by poly000** [comment]
@ShuiHuo 我还想到一种可能，如果你的waylyrics没有和主题同步更新，也就是主窗口没有被命名为 main-window，在最新主题中它不会被设置影响

**Comment by ShuiHuo** [comment]
> RUST_LOG=waylyrics=debug

RUST_LOG=waylyrics=debug waylyrics
2023-10-05T09:06:34.962215Z  INFO waylyrics: process id: 3044998
2023-10-05T09:06:35.014109Z DEBUG waylyrics: config path: "/home/username/.config/waylyrics/config.toml"
2023-10-05T09:06:35.040158Z DEBUG waylyrics: theme path: "/home/username/.local/share/waylyrics/_themes/zhijiao.css"





> 可以麻烦po一下您的
> `~/.local/share/waylyrics/themes/zhijiao.css` 嘛

[zhijiao.css.txt](https://github.com/waylyrics/waylyrics/files/12816478/zhijiao.css.txt)

**Comment by taoky** [comment]
主题文件夹是 `_themes` 而不是 `themes`，确认修改了正确的文件吗？

**Comment by poly000** [comment]
@taoky 但是直角正确加载了

**Comment by ShuiHuo** [comment]
> 主题文件夹是 `_themes` 而不是 `themes`，确认修改了正确的文件吗？

![swappy-20231005-171256](https://github.com/waylyrics/waylyrics/assets/7471938/ddc714de-1e2c-41c2-8953-f0911e2813db)

改对文件的。

**Comment by ShuiHuo** [comment]
还真和 sway 无关，在 KDE 里面也不是透明的。

![Screenshot_20231005_172843](https://github.com/waylyrics/waylyrics/assets/7471938/1ada51c6-49af-44f7-a5b1-395638861013)

**Comment by taoky** [comment]
我猜是自己设置的 gtk 主题把应用的 background-color 设置覆盖了。

**Comment by ShuiHuo** [comment]
> 我猜是自己设置的 gtk 主题把应用的 background-color 设置覆盖了。

　　在 `~/.config/gtk-4.0/gtk.css` 里面把
```
.background {
    background-color: #fafbfc;
}
```
注释掉之后，waylyrics 的背景能正确设置了。 就是没搞懂为什么waylyrics的主题优先级这么低。

**Comment by poly000** [comment]
@ShuiHuo https://docs.gtk.org/gtk4/class.CssProvider.html
奇怪，CssProvider文档说gtk应该在初始化时先加载用户配置

**Comment by taoky** [comment]
GTK4 的窗口默认就同时有 `background` 和 `csd` 这两个 class。因为最近更新加了搜索窗口，所以给主窗口添加了名字，并且 CSS 改成了只对主窗口做透明处理。

测试了一下，GTK 中用户自定义的 CSS 优先级比应用高，并且我没有找到修改的方法，如果需要保留原来的 background，一个 workaround 是在用户 CSS 添加：

```css
window#main-window { background-color: unset; }
```
